---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rock, Paper, Scissors
description: Create your own 'Rock, Paper, Scissors' game.
original_url: https://codeclubprojects.org/en-GB/python/rock-paper-scissors
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Player's Turn
- title: Computer's Turn
- title: Check the Result
- title: 'Challenge: ASCII Art'
- title: 'Challenge: Create a new game'
